name: Build nginx-filesystem-mcp

on:
  push:
    branches: [ main ]
  pull_request:

env:
  GO_VERSION: '1.24.0'  # Alpine not needed for setup-go
  APP_NAME: 'nginx-filesystem-mcp'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Print Go version
        run: go version

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod vendor

      - name: Build binary
        run: |
          mkdir -p ./bin
          go build -mod=vendor -ldflags="-X main.version=${{ github.sha::0:7 }}" -o ./bin/mcp .

      # Optional: skip tests and static analysis as per original
